# This file was generated by GoReleaser. DO NOT EDIT.
cask "tildewire" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "6ea4de7d06c8fd4b689aaec1d820e5b214c8997d074a653c53950a06dbeb623f"
      url "https://github.com/AIluffy/tildewire/releases/download/v#{version}/tildewire_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "99c1462309e446e7e9996754b0a988b6df0544dd34718f139f3d011f559966d5"
      url "https://github.com/AIluffy/tildewire/releases/download/v#{version}/tildewire_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0414f6de490a939859df4e428f90b6aa30e47f44b704a8e48956f1d443987c79"
      url "https://github.com/AIluffy/tildewire/releases/download/v#{version}/tildewire_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e3d3b813ee668a411eb198ec56bf96b833f1e3cc2a192daeff83ff7d843ede60"
      url "https://github.com/AIluffy/tildewire/releases/download/v#{version}/tildewire_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tildewire"
  desc "Terminal daily technical signal radar for developers."
  homepage "https://github.com/AIluffy/tildewire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tildewire"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tildewire"]
    end
  end

  # No zap stanza required

end
