# This file was generated by GoReleaser. DO NOT EDIT.
cask "tildewire" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "de6617aec8bc8c0fd160ed4ea7b12490fab33d5b9d25392186e7ce4a0c4b3c1d"
      url "https://github.com/AIluffy/tildewire/releases/download/v#{version}/tildewire_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5ea44c986e9b9a60864466c1aaf03eadbcc6343ebc53cda958e6745e8e46d80f"
      url "https://github.com/AIluffy/tildewire/releases/download/v#{version}/tildewire_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9973ec817b2fd4f52ba7d438dc133f6628ca087a3bc12dcd2249d5b776d5cced"
      url "https://github.com/AIluffy/tildewire/releases/download/v#{version}/tildewire_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f0502cf82510e845561cdab9788f93c1077ed2d1480e4c89ba3fb358a989013f"
      url "https://github.com/AIluffy/tildewire/releases/download/v#{version}/tildewire_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tildewire"
  desc "Terminal daily technical signal radar for developers."
  homepage "https://github.com/AIluffy/tildewire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tildewire"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tildewire"]
    end
  end

  # No zap stanza required

end
