# This file was generated by GoReleaser. DO NOT EDIT.
cask "tildewire" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "de3b5f7dfa56b8b47bd17a667b605e52868d62a49389429b24f29a238cfaca77"
      url "https://github.com/AIluffy/tildewire/releases/download/v#{version}/tildewire_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3694a4307fd531607632dd42ff769910a6835ab1ff6784f3180c341a871c0142"
      url "https://github.com/AIluffy/tildewire/releases/download/v#{version}/tildewire_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ce36ea4c023aef5c082a7b43aaefcfa9b7ece5245f4c1b9193dcd0cd0efd29c8"
      url "https://github.com/AIluffy/tildewire/releases/download/v#{version}/tildewire_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "61283bee50534769b71b2f6435039da9cd11e872ad138644658dfd62b8a8069c"
      url "https://github.com/AIluffy/tildewire/releases/download/v#{version}/tildewire_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tildewire"
  desc "Terminal daily technical signal radar for developers."
  homepage "https://github.com/AIluffy/tildewire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tildewire"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tildewire"]
    end
  end

  # No zap stanza required

end
