# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tildewire < Formula
  desc "Terminal daily technical signal radar for developers."
  homepage "https://github.com/AIluffy/tildewire"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AIluffy/tildewire/releases/download/v0.1.0/tildewire_0.1.0_darwin_amd64.tar.gz"
      sha256 "32964c81a9ad0e14d7aa21613f52cbfafb2e0899c3d724092a2d334982ed50d0"

      define_method(:install) do
        bin.install "tildewire"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AIluffy/tildewire/releases/download/v0.1.0/tildewire_0.1.0_darwin_arm64.tar.gz"
      sha256 "ebd38008e58f77d60ec5cf2a7f1d6a9f074cb691db045d8e9974b2ebc3ff9ad3"

      define_method(:install) do
        bin.install "tildewire"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AIluffy/tildewire/releases/download/v0.1.0/tildewire_0.1.0_linux_amd64.tar.gz"
      sha256 "2c5016dc972dda02768a1d3a7a08d282a50f161f7d7f5cd049393725c26ce316"
      define_method(:install) do
        bin.install "tildewire"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AIluffy/tildewire/releases/download/v0.1.0/tildewire_0.1.0_linux_arm64.tar.gz"
      sha256 "6c34fc187b5649496a83eabe84f2105b519575b4a751f1c7dcf1edd28585bb68"
      define_method(:install) do
        bin.install "tildewire"
      end
    end
  end

  test do
    system "#{bin}/tildewire", "--version"
  end
end
